# analyze any source files except for packages we did not write ourselves
FILTER_REGEX_INCLUDE: .*src/.*
FILTER_REGEX_EXCLUDE: .*src/navigation/(pure_pursuit|particle_filter)(/.*)?

# don't really want to re-validate files that we already checked
VALIDATE_ALL_CODEBASE: false

DEFAULT_WORKSPACE: .
LINTER_RULES_PATH: .

ENABLE_LINTERS:
  - PYTHON_MYPY
  - PYTHON_RUFF

PYTHON_MYPY_CONFIG_FILE: ./pyproject.toml
PYTHON_RUFF_CONFIG_FILE: ./pyproject.toml
