[tool.black]
line-length = 79
target-version = ['py310']

[tool.isort]
atomic = true
py_version = 310
profile = "black"
line_length = 79

[tool.mypy]
python_version = 3.10

warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

disallow_untyped_defs = true
disallow_untyped_decorators = true

strict_equality = true
strict_concatenate = true

ignore_missing_imports = true
