from typing import Any

class PyOMap:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PyBresenhamsLine:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PyCDDTCast:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def prune(self) -> None: ...

class PyRayMarching:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PyRayMarchingGPU:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PyGiantLUTCast:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class _RangeMethod:
    def set_sensor_model(self, *args: Any, **kwargs: Any) -> None: ...
    def calc_range_many_radial_optimized(self, *args: Any, **kwargs: Any) -> None: ...
    def eval_sensor_model(self, *args: Any, **kwargs: Any) -> None: ...
    def calc_range_repeat_angles_eval_sensor_model(self, *args: Any, **kwargs: Any) -> None: ...
    def calc_range_repeat_angles(self, *args: Any, **kwargs: Any) -> None: ...
    def calc_range_many(self, *args: Any, **kwargs: Any) -> None: ...
