version: "3.8"

services:
  jetson:
    container_name: f1tenth_jetson
    image:  ualbertaformula/f1tenth-jetson
    network_mode: host
    privileged: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - ROS_DOMAIN_ID=42
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///f1tenth/cyclonedds_config.xml
      - IS_JETSON=TRUE
    volumes:
      - ..:/f1tenth:cached
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /usr/local/cuda:/usr/local/cuda
    tty: true
    stdin_open: true
  hardware:
    build:
      context: ..
      dockerfile: docker/Dockerfile.hardware
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=42
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds_config.xml
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - /dev:/dev
      - ${PWD}/cyclonedds_config.xml:/cyclonedds_config.xml
    # image: f1tenth/focal-l4t-foxy:f1tenth-stack
    stdin_open: true
    tty: true
