services:
  dev:
    container_name: f1tenth_dev
    image:  ualbertaformula/f1tenth
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - LIBGL_ALWAYS_INDIRECT=0
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - ROS_DOMAIN_ID=42
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///f1tenth/cyclonedds_config.xml
      - IS_JETSON=FALSE
    volumes:
      - ..:/f1tenth:cached
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    stdin_open: true
  sim:
    image:  ualbertaformula/f1tenth-sim
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - LIBGL_ALWAYS_INDIRECT=0
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - ROS_DOMAIN_ID=42
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds_config.xml
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${PWD}/cyclonedds_config.xml:/cyclonedds_config.xml
    tty: true
    stdin_open: true
