version: "3.8"

services:
  jetson:
    container_name: f1tenth_jetson
    build:
      context: ..
      dockerfile: docker/Dockerfile.jetson
      network: host
    network_mode: host
    privileged: true
    runtime: nvidia
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - DISPLAY=${DISPLAY}
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - ROS_DOMAIN_ID=42
    volumes:
      - ..:/f1tenth:cached
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $SSH_AUTH_SOCK:/ssh-agent
    tty: true
    stdin_open: true
  hardware:
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - /dev:/dev
    image: f1tenth/focal-l4t-foxy:f1tenth-stack
    stdin_open: true
    tty: true
