FROM ros:humble

# using devcontainer is nice cause it'll remap uid's/gid's for us
ARG USERNAME=autonomous
ARG USER_UID=1000
ARG USER_GID=${USER_UID}

SHELL ["/bin/bash", "-c"]

# fix /tmp permissions for sharing unix sockets
RUN chmod 1777 /tmp

# Create the user
RUN groupadd --gid ${USER_GID} ${USERNAME} \
    && useradd --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME} \
    && apt update \
    && apt install -y sudo \
    && echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME}

# install apt packages
COPY docker/deps/packages.txt deps/packages.txt
RUN apt update && apt install -q -y --no-install-recommends \
    $(cat deps/packages.txt) \
    && rm -rf /var/lib/apt/lists/* && apt-get clean

# install python packages
COPY docker/deps/requirements.txt deps/requirements.txt
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install --upgrade --ignore-installed -r deps/requirements.txt

# setup bashrc
RUN echo -e "\nsource /f1tenth/scripts/formula_bashrc.sh" >> /home/${USERNAME}/.bashrc

USER ${USERNAME}
ENTRYPOINT [ "/bin/bash" ]
