name: Build and push dockerfile to Docker Hub(jetson)

on:
  push:
    paths:
      - 'docker/Dockerfile.jetson'
      - 'docker/deps/packages.txt'
      - 'docker/deps/packages-jetson.txt'
      - 'docker/deps/requirements.txt'
      - 'docker/deps/requirements-jetson.txt'

jobs:
  docker-jetson:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --push --platform linux/arm64 -t ualbertaformula/f1tenth-jetson -f ./docker/Dockerfile.jetson .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
