name: Build and push dockerfile to Docker Hub

on:
  push:
    paths:
      - 'docker/**' # only run when docker related files change

jobs:
  docker:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -t jackpar/f1tenth -f ./docker/Dockerfile.dev .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
