name: Build and push dockerfile to Docker Hub(sim)

on:
  push:
    paths:
      - 'docker/Dockerfile.sim' # only run when sim dockerfile changes

jobs:
  docker-sim:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ualbertaformula/f1tenth-sim -f ./docker/Dockerfile.sim .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
