name: ROS 2 Package Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: jackpar/f1tenth
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Packages
        run: |
          ls /opt/ros/humble
          # export AMENT_PREFIX_PATH=""
          # export CMAKE_PREFIX_PATH=""
          # cd dev_ws && colcon build --symlink-install