name: ROS 2 Package Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: jackpar/f1tenth
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Packages
        run: |
          echo -e "\nsource /f1tenth/scripts/formula_bashrc.sh" >> ~/.bashrc && cat ~/.bashrc