name: Build ROS2 Packages(dev)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-dev:
    runs-on: ubuntu-22.04
    container:
      image: ualbertaformula/f1tenth
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Packages
        shell: bash
        run: |
          echo -e "\nsource ./scripts/formula_bashrc.sh" >> ~/.bashrc
          source ~/.bashrc
          rc_build