name: Build ROS2 Packages and Lint Repo

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'

defaults:
  run:
    shell: bash

jobs:
  build-and-lint-cpp:
    runs-on: ubuntu-22.04
    container:
      image: ualbertaformula/f1tenth
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Packages
        run: |
          echo -e "\nsource ./scripts/formula_bashrc.sh" >> ~/.bashrc
          source ~/.bashrc
          rc_build
      # NOTE: don't want to waste action minutes and rebuild everything for
      # compilation database in a separate job, so doing linting and build in same job
      - name: lint cpp code using clang-tidy and clang-format
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        if: ${{ success() }} # only run linting if build was successful
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'  # use .clang-format file
          tidy-checks: '' # use .clang-tidy config file.
          database: './build/'
          thread-comments: 'update'
          no-lgtm: false
          version: '18'
      # we need this fail check since cpp-linter always succeeds even if checks fail
      - name: Check fail
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
  lint-python:
    runs-on: ubuntu-22.04
    container:
      image: ualbertaformula/f1tenth
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Lint python code and check formatting
        uses: super-linter/super-linter/slim@v6.8.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SAVE_SUPER_LINTER_SUMMARY: true
          # FILTER_REGEX_EXCLUDE:
          FILTER_REGEX_INCLUDE: .*src/.* # only analyze source files
          LINTER_RULES_PATH: .
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_MYPY: true
          VALIDATE_PYTHON_ISORT: true
          VALIDATE_PYTHON_FLAKE8: true
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
          PYTHON_MYPY_CONFIG_FILE: pyproject.toml
          PYTHON_ISORT_CONFIG_FILE: pyproject.toml
          PYTHON_FLAKE8_CONFIG_FILE: .flake8
      # - name: lint python code with mypy/flake8 and check formatting with black/isort
      #   uses: ricardochaves/python-lint@v1.4.0
      #   with:
      #     use-pylint: false
      #     use-pycodestyle: false
      #     use-flake8: true
      #     use-black: true
      #     use-mypy: true
      #     use-isort: true
      #     extra-flake8-options: "--config=.flake8"
      #     extra-black-options: "--line-length=79 --target-version=py310"
      #     extra-mypy-options: "--config-file mypy.ini"
      #     extra-isort-options: "--profile black"
