name: ROS 2 Package Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: jackpar/f1tenth
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Packages
        shell: bash
        run: |
          echo -e "\nsource /f1tenth/scripts/formula_bashrc.sh" >> ~/.bashrc
          source ~/.bashrc
          rc_build
# source /opt/ros/humble/setup.bash
# cd dev_ws && colcon build --symlink-install --packages-skip '^zed_.*$' rviz_plugin_zed_od