name: ROS 2 Package Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: jackpar/f1tenth
    steps:
      - name: Checkout code
        uses: actions/checkout@v2